[package]
name = "task_ba"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
